name: amplify_flutter
description: The top level Flutter package for the AWS Amplify libraries.
version: 0.2.1
homepage: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/amplify_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

publish_to: none
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  amplify_storage_plugin_interface: 
    git:
      url: git://github.com/jodafm/amplify-flutter.git
      path: packages/amplify_storage_plugin_interface
      ref: nullSafety_apiName
  amplify_analytics_plugin_interface: 
    git:
      url: git://github.com/jodafm/amplify-flutter.git
      path: packages/amplify_analytics_plugin_interface
      ref: nullSafety_apiName
  amplify_auth_plugin_interface: 
    git:
      url: git://github.com/jodafm/amplify-flutter.git
      path: packages/amplify_auth_plugin_interface
      ref: nullSafety_apiName
  amplify_datastore_plugin_interface: 
    git:
      url: git://github.com/jodafm/amplify-flutter.git
      path: packages/amplify_datastore_plugin_interface
      ref: nullSafety_apiName
  amplify_api_plugin_interface: 
    git:
      url: git://github.com/jodafm/amplify-flutter.git
      path: packages/amplify_api_plugin_interface
      ref: nullSafety_apiName
  amplify_core: 
    git:
      url: git://github.com/jodafm/amplify-flutter.git
      path: packages/amplify_core
      ref: nullSafety_apiName

dev_dependencies:
  flutter_test:
    sdk: flutter
  amplify_api:  
    git:
      url: git://github.com/jodafm/amplify-flutter.git
      path: packages/amplify_api
      ref: nullSafety_apiName
  amplify_analytics_pinpoint:
    git:
      url: git://github.com/jodafm/amplify-flutter.git
      path: packages/amplify_analytics_pinpoint
      ref: nullSafety_apiName
  amplify_auth_cognito:
    git:
      url: git://github.com/jodafm/amplify-flutter.git
      path: packages/amplify_auth_cognito
      ref: nullSafety_apiName
  amplify_datastore:
    git:
      url: git://github.com/jodafm/amplify-flutter.git
      path: packages/amplify_datastore
      ref: nullSafety_apiName
  amplify_storage_s3:
    git:
      url: git://github.com/jodafm/amplify-flutter.git
      path: packages/amplify_datastore
      ref: nullSafety_apiName

flutter:
  plugin:
    platforms:
      android:
        package: com.amazonaws.amplify
        pluginClass: Amplify
      ios:
        pluginClass: Amplify
