name: amplify_storage_s3
description: The Amplify Flutter Storage category plugin using the AWS S3 provider.
version: 0.1.4
homepage: https://github.com/aws-amplify/amplify-flutter/tree/master/packages/amplify_storage_s3

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

publish_to: none
dependencies:
  flutter:
    sdk: flutter
  amplify_storage_plugin_interface:
    git:
      url: git://github.com/jodafm/amplify-flutter.git
      path: packages/amplify_storage_plugin_interface
      ref: withApiName
  plugin_platform_interface: ^2.0.0
  amplify_core:
     git:
      url: git://github.com/jodafm/amplify-flutter.git
      path: packages/amplify_core
      ref: withApiName

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.amazonaws.amplify.amplify_storage_s3
        pluginClass: AmplifyStorageS3Plugin
      ios:
        pluginClass: AmplifyStorageS3Plugin
