name: amplify_api
description: The Amplify Flutter API category plugin, supporting GraphQL and REST operations.
version: 0.2.1
homepage: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/amplify_api

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"


publish_to: none
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  amplify_core: 
    git:
      url: git://github.com/jodafm/amplify-flutter.git
      path: packages/amplify_core
      ref: nullSafety_apiName
  amplify_api_plugin_interface: 
    git:
      url: git://github.com/jodafm/amplify-flutter.git
      path: packages/amplify_api_plugin_interface
      ref: nullSafety_apiName

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.amazonaws.amplify.amplify_api
        pluginClass: AmplifyApiPlugin
      ios:
        pluginClass: AmplifyApiPlugin
