name: amplify_auth_cognito
description: The Amplify Flutter Auth category plugin using the AWS Cognito provider.
version: 0.2.1
homepage: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/amplify_auth_cognito

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"


publish_to: none        
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  amplify_auth_plugin_interface: 
    git:
      url: git://github.com/jodafm/amplify-flutter.git
      path: packages/amplify_auth_plugin_interface
      ref: nullSafety_apiName
  amplify_core: 
    git:
      url: git://github.com/jodafm/amplify-flutter.git
      path: packages/amplify_core
      ref: nullSafety_apiName

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.amazonaws.amplify.amplify_auth_cognito
        pluginClass: AuthCognito
      ios:
        pluginClass: AuthCognito
