name: amplify_api_plugin_interface
description: The Amplify Flutter API category plugin interface.
version: 0.1.4
homepage: https://github.com/aws-amplify/amplify-flutter/tree/master/packages/amplify_api_plugin_interface

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

publish_to: none
dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  uuid: ^3.0.1
  amplify_core: 
    git:
      url: git://github.com/jodafm/amplify-flutter.git
      path: packages/amplify_core
      ref: apiName_version

dev_dependencies:
  flutter_test:
    sdk: flutter
