name: amplify_analytics_pinpoint
description: The Amplify Flutter Analytics category plugin using the AWS Pinpoint provider.
version: 0.1.4
homepage: https://github.com/aws-amplify/amplify-flutter/tree/master/packages/amplify_analytics_pinpoint

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

publish_to: none
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  amplify_core: 
    git:
      url: git://github.com/jodafm/amplify-flutter.git
      path: packages/amplify_core
      ref: apiName_version
  amplify_analytics_plugin_interface: 
    git:
      url: git://github.com/jodafm/amplify-flutter.git
      path: packages/amplify_analytics_plugin_interface
      ref: apiName_version

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.amazonaws.amplify.amplify_analytics_pinpoint
        pluginClass: AmplifyAnalyticsPinpointPlugin
      ios:
        pluginClass: AmplifyAnalyticsPinpointPlugin
