name: amplify_analytics_plugin_interface
description: The platform interface for the analytics module of Amplify Flutter.
version: 0.1.4
homepage: https://github.com/aws-amplify/amplify-flutter/tree/master/packages/amplify_analytics_plugin_interface

environment:
  sdk: ">=2.7.0 <3.0.0"

publish_to: none
dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  amplify_core:
    git:
      url: git://github.com/jodafm/amplify-flutter.git
      path: packages/amplify_core
      ref: withApiName

dev_dependencies:
  flutter_test:
    sdk: flutter
