name: amplify_datastore_plugin_interface
description: The platform interface for the DataStore module of Amplify Flutter.
version: 0.2.1
homepage: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/amplify_datastore_plugin_interface

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

publish_to: none
dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  collection: ^1.15.0
  date_time_format: ^2.0.1
  uuid: ^3.0.1
  amplify_core: 
    git:
      url: git://github.com/jodafm/amplify-flutter.git
      path: packages/amplify_core
      ref: nullSafety_apiName

dev_dependencies:
  flutter_test:
    sdk: flutter
